### ISSUE TITLE
Smith~Hartman, Exp Gerontology, 2016 - to add/process

### ISSUE THREAD

**Issue by abarysh** [baryshnikova-lab/YeastPhenome.org#71]
Paper to add/process if relevant: http://www.sciencedirect.com/science/article/pii/S0531556516301085

I can't access it right now (Princeton does not subscribe to Experimental Gerontology).

@bricha2 - can you see if you can access it from your institution? If yes, could you attach a PDF here?

**Comment by bricha2** [comment]
[1-s2.0-S0531556516301085-main.pdf](https://github.com/baryshnikova-lab/YeastPhenome.org/files/298220/1-s2.0-S0531556516301085-main.pdf)
[mmc3.pdf](https://github.com/baryshnikova-lab/YeastPhenome.org/files/298219/mmc3.pdf)
 
I could access them!

**Comment by abarysh** [comment]
Got it, thanks!
