### ISSUE TITLE
Error on yp-dev when trying to use the libChEBIpy library

### ISSUE THREAD

**Issue by abarysh** [baryshnikova-lab/YeastPhenome.org#72]
@svenmh - I'm attaching the screenshot. To reproduce the error, you can go to http://yeastphenome-dev.princeton.edu/admin/conditions/conditiontype/170/ , insert 53745 into the chebi_id field and click save.

![error](https://cloud.githubusercontent.com/assets/11416566/14970140/b7ea0eb8-1094-11e6-8fd7-bc352bf3fa4e.png)

**Comment by svenmh** [comment]
Ok, give it a try on yp-dev, if it work there I'll fix it on yp Tuesday.

**Comment by abarysh** [comment]
Yep, works great on yp-dev

**Comment by svenmh** [comment]
I did the same on yp.  Plus I pushed an updated README.md file.

**Comment by abarysh** [comment]
Yep, works great on yp as well. Closing the issue.
