### ISSUE TITLE
Conditions without conditionsets

### ISSUE THREAD

**Issue by abarysh** [baryshnikova-lab/YeastPhenome.org#73]
I was going through the list of existing conditions in the database and noticed that a few conditions are not associated with any conditionsets and, therefore (by definition) are not associated with any datasets.

In some cases, I know it's because I ended up creating a new condition (with a different dose) and used that one, but in a few cases only 1 dose exists and it's not used. So I was wondering if it is safe to remove these or if there's a reason why they exist.

For example, @ChristieChang -- I think you added the FM4-64 conditiontype and condition, but it looks like it's not linked to any conditionsets and datasets. Do you remember why that is? Is it safe to delete this and other cases like this?

http://www.yeastphenome.org/admin/conditions/conditiontype/373/

Let me know!

**Comment by abarysh** [comment]
I deleted all the "orphan" conditions that I recognized as inserted by me. But I think these ones are @ChristieChang 's:

FM 4-64 dye
mercaptoethanol [30 nmol/l]
dimethyl sulfoxide [6 ul/ml]
dithioerythritol [4 nmol/l]

Thanks!

**Comment by ChristieChang** [comment]
Yes, I must have accidentally added those. I think they are from when I added a new chemical/condition and thought I made a mistake, and then I ended up creating a new one and didn't delete the old one (I didn't realize I could). Anastasia, can you delete those 4 for me? I don't want to accidentally delete the non "orphan" ones.

**Comment by abarysh** [comment]
Yep, sounds great, thanks!
