### ISSUE TITLE
DTT condition type error

### ISSUE THREAD

**Issue by ChristieChang** [baryshnikova-lab/YeastPhenome.org#74]
I found this error for the condition type for the drug DTT. I think this is probably due to ChEBI/PubChem mapping issues, but I'm not sure.

DTT (dithiothreitol) seems to have been merged with DTE (dithioerythritol). DTE is an epimer of DTT, but they shouldn't be listed as the same condition type.

I think the problem stems from this: 
dithiothreitol entry in YeastPhenome has Chebi ID:[17456 ](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=17456)(DTE) and Pubchem id: [446094 ](https://pubchem.ncbi.nlm.nih.gov/compound/DL-1_4-Dithiothreitol)(DTT).
[http://yeastphenome.org/admin/conditions/conditiontype/235
](http://yeastphenome.org/admin/conditions/conditiontype/235)

The correct Chebi ID for DTT is [42170](http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:42170
)

Added complication is that ChEBI also lists the L enantiomer of DTT as a separate ID ([42106](http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:42106)). Sigma sells the DL mix, and ChEBI says that both forms are reactive and often used as a mix, so what's used in most experiments is likely the mixture. I think it's probably okay to just use the D form Chebi ID (42170) though?

Anastasia, does fixing this simply mean changing the Chebi ID on [this page](http://yeastphenome.org/admin/conditions/conditiontype/235/)? I can do that if it is, but if it's more involved than that, it might be better for you to do it.

**Comment by abarysh** [comment]
Great catch! To fix it, we should first check whether the 3 papers that are linked to the chemical (http://www.yeastphenome.org/papers/?q=dithiothreitol) are in reality using the same chemical (DTE or DTT) or some are using DTE whereas others are using DTT. If they are using the same, we can just fix the conflicting info on the conditiontype page. If they are using different chemicals, then we have to keep what we have, create another conditiontype and re-link the papers to the correct conditiontype.

@ChristieChang Do you want to try it out? If you have trouble or are not sure how to proceed, let me know, I can help out for sure. Feel free to post questions here.

**Comment by ChristieChang** [comment]
Ok, I will check each paper and then change as needed. My guess is that all the papers use DTT (and not DTE), so it should be an easy change.

**Comment by abarysh** [comment]
Great! Let me know if it gets complicated.

**Comment by ChristieChang** [comment]
All three papers used DTT, so I changed the Chebi ID to 42170 on the Condition Type. All the corresponding Condition Sets and Conditions were auto-updated with the new name, so I think it went through correctly.

**Comment by abarysh** [comment]
Cool! One quick question: you said the correct CheBI ID for DTT is 42170. Why not 17456? The structure of the 2 entries seems to be the same, but I generally go with the most general name, if I can (e.g., the one that doesn't mention D- or L- enantiomers, unless the chemical in the paper actually is that specific).

**Comment by abarysh** [comment]
Sorry, ignore last comment, I made the same mistake again :)

**Comment by ChristieChang** [comment]
I chose 42170 because it was listed in the PubChem entry, but now that I'm looking at it, I think it's too specific, since it's the D- form. 

I think the correct Chebi entry should be [18320](http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:18320), which is 1,4-dithiothreitol. It is the parent term for D- and L- forms. DTT is listed as a synonym.

I'm going to change it to 18320 unless you think I shouldn't.

**Comment by abarysh** [comment]
Yeah, I think 18320 is best.

**Comment by ChristieChang** [comment]
Ok, I changed it.
