### ISSUE TITLE
adding multiple data files to single dataset?

### ISSUE THREAD

**Issue by ChristieChang** [baryshnikova-lab/YeastPhenome.org#77]
For PMID 12134085, the dataset is split into two separate PDFs. Is there a way to link the two PDFs to the same dataset? I couldn't figure out how, so I have just duplicated the dataset and added the two files separately, with an explanation in the private notes. 

Also, as I noted, it may be worth requesting non-PDF versions of the table, since I don't think the data is provided in a way that makes it easy to extract out the info we want (I'm definitely not an expert on PDF-table conversions though, and always have trouble with them, so maybe it is usable as is!).

**Comment by abarysh** [comment]
Yep, good point. To enable situations like this, I made the "link" field bigger now, and so you should be able to paste multiple URLs there for any given source. Could you check if that solves this issue? Basically, when a single dataset is linked to multiple PDFs/URLs, you should be able to paste all of the URLs into the link field, one per line.

**Comment by ChristieChang** [comment]
This works great. I just put both links in the same source, each on a new line.
