### ISSUE TITLE
Condition set number display?

### ISSUE THREAD

**Issue by ChristieChang** [baryshnikova-lab/YeastPhenome.org#78]
Hi Anastasia,

I accidentally added some condition sets with just YPD, and wanted to delete them, but it was too hard to find them from the list of condition sets, since there are >8000. Luckily, it was in my "recent actions", so I was able to delete them. Can you display the condition set number like you have in the condition menu? And make it sortable?

**Comment by abarysh** [comment]
This should be fixed now

**Comment by ChristieChang** [comment]
Great, thanks!
